
# Loads default set of integrations. Do not remove.
default_config:

alarm_control_panel:
  - platform: inim_alarm
    password: !secret inim_alarm_password
    username: !secret inim_alarm_username
    client_id: '123456'
    device_id: '789012'
    # scenarios: # use this to override default scenario ids
    #   armed_away: 0
    #   disarmed: 1
    #   armed_night: 2
    #   armed_home: 3